config/routes.rb
Rails.application.routes.draw do

  resources :stores do
    resources :locations
  end

  root to: "pages#home"
  get 'test', to: "stores#test"

  resources :pages
  get 'home', to: 'pages#home'
  get 'reviews', to: 'pages#reviews'
  get 'areas', to: 'pages#areas'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'map_page', to: 'pages#map_page'

end

app/models/location.rb
class Location < ActiveRecord::Base

	belongs_to :store, foreign_key: "store_id"

	validates :address, presence: true

end

app/models/store.rb
class Store < ActiveRecord::Base

  has_many :locations, dependent: :destroy
  accepts_nested_attributes_for :locations

  def self.search(search)
    search_condition = "%" + search + "%"
    where("name like ? or description like ?", search_condition, search_condition)
  end


	before_validation :regularize_phone_number

	def regularize_phone_number
		self.phone_number = phone_number.gsub(/[^0-9]/, "")
	end

  	has_attached_file 	:picture, 
  						:styles => { :medium => "300x300>", :thumb => "100x100>" }, 
  						url: "/assets/images/stores/:id/:style/:basename.:extension",
  						path: "/:rails_root/public/assets/images/stores/:id/:style/:basename.:extension",
  						:default_url => "/missing.png"
  	validates :web_address, presence: true
  	validates :description, presence: true,
  							length: { minimum: 15 }	
  	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
  	
  	validates :name, presence: true,
					 length: { minimum: 3 }
  	
  	validates :phone_number, presence: true,
  							 length: { is: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @store = Store.find(params[:store_id])
    @location = Location.create(location_params)


    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :latitude, :longitude)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
end

def about
end

def contact
end

def areas
end

def reviews
end

def map_page
end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  
  @location = Location.all
  @geojson = Array.new

  @location.each do |location|
    @geojson << { type: 'Feature',
                  geometry: {
                    type: 'Point',
                    coordinates: [location.longitude, location.latitude]
                    },
                  properties: {
                    name: store.name,
                    address: store.address,
                    :'marker-color'=> '#00607d',
                    :'marker-symbol'=> 'circle',
                    :'marker-size'=> 'medium'
                  }
                }
  end

  def index
    if params[:search]
      @stores = Store.search(params[:search]).order(name: :asc)
    else
      @stores = Store.order(name: :asc)
    end
  end

  def search
    @stores = Store.search params[:search]
  end

  def test
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])
  end

  def home
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :description, :picture, :web_address, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TokyoBoozerApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyBaWwfRL4VUWtUEJLXKImHusNayEFoph3s" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= home_path %>">Tokyo Boozer</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Areas<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Shinjuku</a></li>
                  <li><a href="#">Shibuya</a></li>
                  <li><a href="#">Ikebukuro</a></li>
                  <li class="divider"></li>
                  <li><%= link_to "All areas", stores_path %></li>
                  <li class="divider"></li>
                  <li><a href="#">Area Descriptions</a></li>
              </ul>
            </li>
            <li><%= link_to "Reviews", reviews_path  %></li>
            <li><%= link_to "About", about_path  %></li>
            <li><%= link_to "Contact", contact_path  %></li>
          </ul>
          <%= form_tag stores_path, method: 'get' do %>

          <% end %>


          
          <!-- search bar -->
          <%= form_tag stores_path, method: 'get', class: "navbar-form navbar-right visible-lg visible-md" do %>
            <div class="form-group">
              <%= text_field_tag :search, params[:search], placeholder: "Keyword", id: 'search_field', class: "form-control" %>
            </div>
              <%= submit_tag 'Search', name: nil, class: "btn btn-default" %>
          <% end %>

          <form class="navbar-form navbar-left visible-sm visible-xs" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Keyword">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
 <!--         =begin <%= form_tag new_store_path   do  %>
            <input type="text" class="form-control" placeholder="Keyword">
          <% end %> --> 
          </form>
        </div>
      </div>
    </div><!--/topnav-->  

    <!--start content-->
    <div class="container">
      <div class="row">
        <div class="col-md-9">

          <%= bootstrap_flash %>
          <%= yield %>

        </div>

        <div class="col-md-3">
            <!-- Sidebar Booze navigator is here -->
            <div class="affix">
                <div class="well sidebar-nav visible-lg visible-md">
                  <h3>Booze Navigator</h3>
                  <ul class="nav nav-list">
                    <li class="nav-header">Popular Areas</li>
                    <li><%= link_to "Shibuya", map_page_path  %></li>
                    <li><%= link_to "Shinjuku", "/path2"  %></li>
                    <li><%= link_to "Ikebukuro", "/path3"  %></li>
                    <li><%= link_to "Nakano", "/path3"  %></li>
                    <li><%= link_to "Shimokitazawa", "/path3"  %></li>
                    <br />
                    <li class="nav-header">Top Keywords</li>
                    <li><a href="">Punk bar</a></li>
                    <li><a href="">house club</a></li>
                    <li><a href="">artsy pub</a></li>
                  </ul>
                </div><!--/.well -->
            </div><!--/sidebar nav-->

            <!-- ads should go here
            <div class="visible-lg visible-md">
              <%= image_tag("ad_placeholder120.png") %>
            </div>     --> 

            <!-- for responsiveness -->
            <div class="visible-xs visible-sm">
                <div style="padding: 20px 0px 0px 20px;"><%= image_tag("250x250adPlaceholder.png") %></div>
            </div>      

        </div><!--/span-->
      </div><!--/row-->
    
      <footer>
        <p>&copy; Aaron Burdick 2015</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/pages/about.html.erb
<%= image_tag("8-bit-beer.gif", size: "200x200") %>
<h3>Why did I make Tokyo boozer?</h3>
<p>It's really quite simple really. Finding a good bar in Tokyo is a real pain on the internet. I found myself saying this a lot:</p>

<blockquote><p>If only tabelog didn't show me izakayas when I want to drink somewhere that isn't an izakaya. I'm looking for some place where I can mingle.</p></blockquote>

<p>Hopefully with this website, you'll be able to find something that fits you, rather than ending up at a joint that will charge you 2000 yen for a whiskey.</p>

app/views/pages/contact.html.erb
<h2>Contact Information</h2>

<div class="container">
	<p>Questions, comments, or Nihonshuu recommendations should be sent to:</p>
	<div class ="row">
		<h3>Mail</h3>
		<div class="col-sm-4">
			<h4>English</h4>
			<address>
			<strong>Aaron Burdick</strong><br />
			Tokyo-to Shinjuku-ku Kamiochiai 3-3-5<br />
			Maisutairu Nakai 204<br />
			</address>
		</div>
		<div class="col-sm-5">
			<h4>日本語</h4>
			<address>
			<strong>バーディクアーロン</strong><br />
			東京都新宿区上落合３丁目５番５号<br />
			マイスタイル中井２０４<br />
			</address>
		</div>		
	</div>
	<div class="row">
		<h3>E-mail</h3>
		<div class="col-xs-9">
			<address>
			<strong>Aaron Burdick</strong><br />
			<a href="mailto:burdick.aaron@gmail.com?Subject=Re:Tokyo%20Boozer" target="_top">burdick.aaron@gmail.com</a>
			</address>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Featured Bar</h1>
	<p>AOYAMA TUNNEL</p>
	<p>ありそうで無かったラウンジ、Aoyama Tunnelへようこそ。最高の音楽と共にゆったりと過ごせるお店です。
			  	皆様のお越しをお待ちしております。–PartyやDjについて等随時募集しておりますので下記連絡先、担当:
			  	植松までお気軽にお問い合わせ下さい。尚、仕様機材は以下の通りです。
	<a class="btn btn-primary btn-large">
	Learn more
    </a>
　  <br />
	</p>
</div>

app/views/pages/map_page.erb
<h2>Somebody's poisoned the waterhole</h2>
<div id="map-container">
	<div id="map-canvas"></div>
</div>

app/views/pages/reviews.html.erb
<p>Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. Reviews go here. </p>

app/views/stores/_form.html.erb
<%= form_for @store, :html => { multipart: true, :class => "form-horizontal store" } do |f| %>

    <% if @store.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @store.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:name]) %>
  </div>
  
  <div class="control-group">
      <%= f.label :phone_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone_number, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:phone_number]) %>
  </div>
  
  <div class="control-group">
    <%= f.label "Web URL", :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :web_address, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:web_address]) %>
  </div>  
  
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%= error_span(@store[:description]) %>
  </div>
  
  <div class="control-group">
    <%= f.label :picture %>
    <div class="controls">
      <%= f.file_field :picture %>
    </div>
    <%= error_span(@store[:picture]) %>
  </div>

<br />
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            stores_path, :class => 'btn btn-default' %>

<% end %>

app/views/stores/_map.html.erb
<iframe
  width="300"
  height="300"
  frameborder="1" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDvlbT4viOOGx6VWKAyCW-isYpG3skvgWc
    &q=tokyo">
</iframe>
<p>View on <a href="https://www.google.co.jp/maps/place/tokyo"> google maps.</p></a>

app/views/stores/_storedetails.html.erb
<%- model_class = Store -%>

<div class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title"><%= @store.name %></h1>
    </div> <!--/panel heading-->
    <div class="panel-content">
      <div title="description">
        <strong><%= model_class.human_attribute_name(:description) %>:</strong><br />
        <%= @store.description %><br />
      </div>
      <div title="URL">
        <strong>URL:</strong><br />
        <a href="<%= @store.web_address %>"><%= @store.web_address %></a><br />
      </div>
      <div title="phone number">
        <strong>Phone:</strong><br />
        <%= @store.phone_number %><br />
      </div>
      <div title="picture">
        <%= image_tag @store.picture.url(:thumb) %>
      </div>
    </div> <!--/panel content-->
</div> <!--/panel-->

<!--Start buttons-->
<%= link_to t('.back', :default => t("helpers.links.back")),
              stores_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_store_path(@store), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              store_path(@store),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/stores/edit.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stores/index.html.erb
<!-- If search then show user the count -->
<% if params[:search] and @stores.count(:name) > 0 %>
  <p class="text-primary"><%= 'Search found ' + pluralize(@stores.count(:name), 'result') + ':' %></p>
<% elsif @stores.count(:name) < 1 %>
  <p class="text-warning">No results found. Perhaps try another keyword?</p>
<% end %>

<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <!-- <th><%= model_class.human_attribute_name(:created_at) %></th> -->
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.name, store_path(store) %></td>
        <td class="visible-lg visible-md">
          <% if store.description.length > 200 %>
            <%= store.description[0,200] + "..." %>
            <%= link_to "[more details]", store_path(store) %>
          <% else %>
            <%= store.description %>
            <%= link_to "[more details]", store_path(store) %>
          <% end %>
        </td>

        <td class="visible-sm visible-xs">
          <% if store.description.length > 100 %>
            <%= store.description[0,100] + "..." %>
            <%= link_to "[more details]", store_path(store) %>
          <% else %>
            <%= store.description %>
            <%= link_to "[more details]", store_path(store) %>
          <% end %>
        </td>
        <!-- <td><%=l store.created_at %></td> -->
        <td>
          <!-- start buttons -->
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_store_path(store), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      store_path(store),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_store_path,
            :class => 'btn btn-primary' %>

app/views/stores/new.html.erb
<%- model_class = Store -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/stores/show.html.erb
<div class="container visible-lg">
  <div class="row">
    <div class="col-md-5">
      <%= render partial: 'storedetails' %>
    </div>
    <div class="col-md-4">
      <div style="padding-left: 20px;"><%= render partial: 'map' %></div>
    </div>
  </div>
</div>

<div class="container visible-md">
  <div class="row">
    <div class="col-md-5">
      <%= render partial: 'storedetails' %>
    </div>
    <div class="col-md-4">
      <%= render partial: 'map' %>
    </div>
  </div>
</div>

<div class="container visible-sm visible-xs">
  <div class="row">
    <div class="col-md-5">
      <%= render partial: 'storedetails' %>
    </div>
    <div class="col-md-4">
      <div style="padding-top: 20px;"><%= render partial: 'map' %></div>
    </div>
  </div>
</div>

app/views/stores/test.html.erb
<div class="dropdown">
  <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Dropdown trigger
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
    ...
  </ul>
</div>